eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true

webClient:
  url: http://localhost:8070
