server:
  port: 8090

  http2:
    enabled: true

spring:
  application:
    name: eventor-gateway

  profiles:
    active: dev

  jwt:
    secret: ae2d34485b06523251b0cf111013481ef501749742a11b927f92eb7d9a048eec5fd22976673af2d7fd4fe93428d4f3301d60ad10164ffc3cea29743fe5906909

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR