eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@eventor-eureka:8761/eureka
  instance:
    prefer-ip-address: true

webClient:
  url: http://eventor-auth:8070